services:
  app:
    build: .
    container_name: home-library-rest-service
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '4000:4000'
    networks:
      - home-library-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_library
    ports:
      - '5432:5432'
    networks:
      - home-library-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d home_library']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
networks:
  home-library-network:

volumes:
  postgres_data:
